### ISSUE TITLE
I'm very interested in joining the project，Can I develop components with you？

### ISSUE THREAD

**Issue by staticdeng** [IronPans/bee-mobile#5]

**Comment by IronPans** [comment]
@dzfrontend Of course, welcome

**Comment by sherxia92** [comment]
这个ui做的很赞！

**Comment by sherxia92** [comment]
请问作者对pc和移动web 用同一套ui自适应 有什么了解或或者心得么？   我看ant-design-pro就是一个pc移动通用的ui，但是做的还不是太好。

**Comment by staticdeng** [comment]
How many contact ways do you have?I want to discuss with you，and my qq is 1301829682
