### ISSUE TITLE
create-react-app 更新了  bee-mobile 用不了。。。。  救命

### ISSUE THREAD

**Issue by sunzhongt** [IronPans/bee-mobile#7]
create-react-app 更新了  bee-mobile 用不了。。。。  救命  通过 npm install bee-mobile -S在项目中下载 再 通过import {Button} from 'bee-mobile';的方式使用， 这样没有样式效果。。。。

之后  使用 bee-mobile 的 官方 给的 create-bee-mobile ，怎么使用npm run build   之后
![image](https://user-images.githubusercontent.com/33446938/48052416-d22fb300-e1e2-11e8-8098-fef711c33120.png)  是空白

**Comment by chang-ke** [comment]
有可能是你没引入样式文件

**Comment by IronPans** [comment]
@sunzhongt 看看是不少样式没引入
